name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: set version
        id: set_version
        run: |
          version=$(date +'%Y%m%d.%H%M%S')
          echo "version=$version" >> "$GITHUB_OUTPUT"
          printf '{"version": "%s" }' "$version" > public/version.json

      - name: Build
        run: |
          npm ci && npm run build
          cp dist/index.html dist/404.html

      - name: Update pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
      - name: Run tests
        run: |
          npx playwright install --with-deps chromium
          npm run test:coverage
      - name: Update coverage
        run: |
          set -euo pipefail
          # Read the lines coverage percentage from the summary JSON
          coverage=$(jq '.total.lines.pct' coverage/coverage-summary.json)
          coverage=$(printf "%.2f" "$coverage")
          # decide color (red if below 80)
          color=$(echo "$coverage < 80" | bc | awk '{if ($1) print "red"; else print "green"}')
          echo "Posting coverage: $coverage% (color: $color)"

          # POST the raw coverage JSON as a form file and include metadata as query params
          # Use verbose output and --fail so the job fails on HTTP errors and the logs show the server response
          curl -S --fail -v -X POST \
            -H "Authorization: Bearer ${{ secrets.FACTORY_API_KEY }}" \
            -F "coverage=@coverage/coverage-summary.json;type=application/json" \
            "https://pizza-factory.cs329.click/api/badge/${{ secrets.NET_ID }}/jwtpizzacoverage?label=Coverage&value=${coverage}%25&color=${color}" \
            -o /tmp/coverage-post.response || (echo "Coverage POST failed; see curl output above" && false)

          echo "Badge update response:" && cat /tmp/coverage-post.response || true
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
